name: Flutter Release Build

on:
  push:
    branches:
      - main

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Setup Flutter
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'

    # Step 3: Install dependencies
    - name: Flutter Pub Get
      run: flutter pub get

    # Step 4: Setup Android Keystore
    - name: Setup Keystore
      run: |
        mkdir -p android
        echo ${{ secrets.KEYSTORE_BASE64 }} | base64 --decode > android/keystore.jks

    # Step 5: Build release APK
    - name: Build Release APK
      run: flutter build apk --release --no-shrink

    # Step 6: Upload APK artifact
    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release.apk
        path: build/app/outputs/flutter-apk/app-release.apk
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          flutter build apk --release \
          --flavor production \
          --dart-define=KEYSTORE_PASSWORD=$KEYSTORE_PASSWORD \
          --dart-define=KEY_ALIAS=$KEY_ALIAS \
          --dart-define=KEY_PASSWORD=$KEY_PASSWORD

      # 6. Upload Release APK as artifact
      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
