name: Flutter Release Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Flutter (latest stable version)
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.6' # Latest stable version, replace if needed

      # 3. Install dependencies
      - name: Flutter Pub Get
        run: flutter pub get

      # 4. Build release APK
      - name: Build Release APK
        run: flutter build apk --release

      # 5. Upload Release APK as artifact
      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
