name: Flutter Release Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2️⃣ Setup Flutter (explicit version)
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.13.7'  # <-- specify exact stable version

    # 3️⃣ Install dependencies
    - name: Flutter Pub Get
      run: flutter pub get

    # 4️⃣ Ensure android folder exists (for keystore)
    - name: Ensure android folder
      run: mkdir -p android

    # 5️⃣ Decode Keystore (optional)
    - name: Decode Keystore
      if: ${{ secrets.KEYSTORE_BASE64 }}
      run: echo ${{ secrets.KEYSTORE_BASE64 }} | base64 --decode > android/keystore.jks

    # 6️⃣ Build release APK
    - name: Build Release APK
      run: flutter build apk --release

    # 7️⃣ Upload APK as artifact
    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release.apk
        path: build/app/outputs/flutter-apk/app-release.apk

    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release.apk
        path: build/app/outputs/flutter-apk/app-release.apk
