name: Flutter Release Build with Signing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.6' # latest stable version

      # 3. Install dependencies
      - name: Flutter Pub Get
        run: flutter pub get

      # 4. Decode Keystore from GitHub Secret
      - name: Setup Keystore
        run: |
          echo ${{ secrets.KEYSTORE_BASE64 }} | base64 --decode > android/keystore.jks

      # 5. Build Release APK (signed)
      - name: Build Release APK
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          flutter build apk --release \
          --flavor production \
          --dart-define=KEYSTORE_PASSWORD=$KEYSTORE_PASSWORD \
          --dart-define=KEY_ALIAS=$KEY_ALIAS \
          --dart-define=KEY_PASSWORD=$KEY_PASSWORD

      # 6. Upload Release APK as artifact
      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
