name: Flutter Build & Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout code
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Setup Flutter
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'

    # 3. Enable Flutter dependencies
    - name: Flutter Pub Get
      run: flutter pub get

    # 4. Analyze code
    - name: Flutter Analyze
      run: flutter analyze

    # 5. Run tests (if any)
    - name: Flutter Test
      run: flutter test

    # 6. Build APK (debug)
    - name: Build APK (Debug)
      run: flutter build apk --debug

    # 7. Upload APK as artifact
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug.apk
        path: build/app/outputs/flutter-apk/app-debug.apk
