name: Flutter Release Build

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'

    - name: Flutter Pub Get
      run: flutter pub get

    - name: Build Release APK
      run: |
        echo ${{ secrets.KEYSTORE_BASE64 }} | base64 --decode > android/keystore.jks
        flutter build apk --release

    - name: Upload Release APK
      uses: actions/upload-artifact@v4   # <-- یہاں v4 استعمال کریں
      with:
        name: app-release.apk
        path: build/app/outputs/flutter-apk/app-release.apk
